import {z} from 'zod';
const short=z.string().max(200),long=z.string().max(3000),id=z.string().max(100);
export const designSchema=z.object({background:short,primary:short,font:z.enum(['Georgia','Arial','Verdana']),radius:z.number().min(0).max(40),columns:z.number().int().min(1).max(3),fontSize:z.number().min(12).max(24),spacing:z.number().min(0).max(40),banner:short,header:z.enum(['center','left']),card:z.enum(['card','list'])});
export const itemSchema=z.object({id,categoryId:id,name:short,ar:short,description:long,descriptionAr:long,price:z.number().min(0).max(100000),discount:z.number().min(0).max(100000),image:long,available:z.boolean(),featured:z.boolean(),ingredients:long,allergens:short,calories:z.number().min(0).max(10000),spicy:z.number().min(0).max(3),dietary:short,hidden:z.boolean()});
export const menuSchema=z.object({id,name:short,slug:z.string().regex(/^[a-z0-9-]+$/).max(100),design:designSchema,categories:z.array(z.object({id,name:short,ar:short})).max(100),items:z.array(itemSchema).max(1000)});
export const stateSchema=z.object({revision:z.number().int(),profile:z.object({setupCompleted:z.boolean().default(false),name:short,ar:short,description:long,descriptionAr:long,phone:short,address:long,hours:long,social:long,logo:long,branches:z.array(short).max(30)}),menus:z.array(menuSchema).min(1).max(30),themes:z.array(z.object({id,name:short,design:designSchema})).max(50)});
export type Menu=z.infer<typeof menuSchema>;export type Item=z.infer<typeof itemSchema>;export type State=z.infer<typeof stateSchema>;
export const baseDesign={background:'#faf7ee',primary:'#3e6347',font:'Georgia' as const,radius:12,columns:1,fontSize:16,spacing:16,banner:'Seasonal ingredients. Thoughtfully made.',header:'center' as const,card:'card' as const};
export const templatePresets=[
  {name:'Modern Restaurant',background:'#faf7ee',primary:'#3e6347',font:'Georgia' as const,radius:12,columns:1,fontSize:16,spacing:16,banner:'Seasonal ingredients. Thoughtfully made.',header:'center' as const,card:'card' as const,description:'Warm olive tones with elegant serif typography. Perfect for upscale casual dining.'},
  {name:'Luxury Dining',background:'#171b18',primary:'#e4cd95',font:'Georgia' as const,radius:4,columns:1,fontSize:16,spacing:20,banner:'An exclusive dining experience.',header:'center' as const,card:'card' as const,description:'Dark sophistication with gold accents. Ideal for fine dining restaurants.'},
  {name:'Minimal Café',background:'#ffffff',primary:'#333333',font:'Arial' as const,radius:8,columns:2,fontSize:15,spacing:14,banner:'',header:'left' as const,card:'list' as const,description:'Clean and modern with generous whitespace. Great for cafés and bistros.'},
  {name:'Burger Restaurant',background:'#fff2de',primary:'#8d4025',font:'Arial' as const,radius:16,columns:2,fontSize:15,spacing:12,banner:'Fresh burgers, made to order.',header:'center' as const,card:'card' as const,description:'Warm and inviting with bold earthy tones. Built for casual eateries.'},
  {name:'Pizza Restaurant',background:'#fbebe3',primary:'#9c422b',font:'Georgia' as const,radius:20,columns:2,fontSize:15,spacing:14,banner:'Wood-fired perfection.',header:'center' as const,card:'card' as const,description:'Italian-inspired warmth with rich terracotta colors.'},
  {name:'Coffee Shop',background:'#efe7dc',primary:'#5a3e2a',font:'Georgia' as const,radius:10,columns:1,fontSize:16,spacing:18,banner:'Crafted with care, served with love.',header:'center' as const,card:'card' as const,description:'Cozy and inviting with rich brown tones. Perfect for coffee houses.'},
  {name:'Bakery',background:'#fff0ed',primary:'#94614f',font:'Georgia' as const,radius:14,columns:2,fontSize:15,spacing:12,banner:'Fresh from the oven daily.',header:'center' as const,card:'card' as const,description:'Soft and warm with blush undertones. Sweet as your pastries.'},
  {name:'Fast Food',background:'#fff9d9',primary:'#473d27',font:'Arial' as const,radius:20,columns:2,fontSize:14,spacing:10,banner:'Quick, fresh, delicious.',header:'center' as const,card:'card' as const,description:'Bold and energetic with high contrast. Built for speed and clarity.'},
  {name:'Arabic Restaurant',background:'#f0e9d7',primary:'#775b2e',font:'Georgia' as const,radius:8,columns:1,fontSize:17,spacing:18,banner:'أطباق تراثية أصيلة',header:'center' as const,card:'card' as const,description:'Traditional warmth with golden amber tones. Supports full RTL layout.'},
  {name:'Dark Elegant',background:'#192027',primary:'#ead9b3',font:'Georgia' as const,radius:6,columns:1,fontSize:16,spacing:20,banner:'A refined evening experience.',header:'center' as const,card:'card' as const,description:'Deep navy elegance with champagne accents. For upscale evening dining.'},
  {name:'Colorful Casual',background:'#edf4f0',primary:'#3c7365',font:'Arial' as const,radius:18,columns:2,fontSize:14,spacing:12,banner:'Good food, good vibes.',header:'center' as const,card:'card' as const,description:'Fresh and vibrant with teal highlights. Fun for family restaurants.'},
] as const;
export function seed():State{const categoryId=crypto.randomUUID();return {revision:0,profile:{setupCompleted:false,name:'Olive & Ember',ar:'زيتون وجمر',description:'Seasonal Mediterranean cooking, made with care.',descriptionAr:'مأكولات متوسطية موسمية، محضرة بعناية.',phone:'+962 6 555 0100',address:'Downtown, Amman',hours:'Daily · 9:00 AM – 11:00 PM',social:'',logo:'',branches:['Downtown']},themes:[],menus:[{id:crypto.randomUUID(),name:'Main Menu',slug:'main-menu',design:{...baseDesign},categories:[{id:categoryId,name:'From the kitchen',ar:'من المطبخ'}],items:[['Burrata & heirloom tomato','بوراتا وطماطم',14,'Creamy burrata, ripe tomatoes, basil and olive oil.'],['Wild mushroom risotto','ريزوتو الفطر',24,'Arborio rice, woodland mushrooms and aged parmesan.'],['Wood-fired sea bass','سمك قاروص مشوي',32,'Fresh sea bass, lemon, herbs and seasonal vegetables.']].map(([name,ar,price,description])=>({id:crypto.randomUUID(),categoryId,name:String(name),ar:String(ar),price:Number(price),description:String(description),descriptionAr:'',discount:0,image:String(name).startsWith('Burrata')?'https://images.unsplash.com/photo-1760023570385-ee484f7076b3?auto=format&fit=crop&w=800&q=80':String(name).startsWith('Wild')?'https://images.pexels.com/photos/5638527/pexels-photo-5638527.jpeg?auto=compress&w=800':'',available:true,featured:false,ingredients:'',allergens:'',calories:0,spicy:0,dietary:'',hidden:false}))}]}}
