import {z} from 'zod';
const short=z.string().max(200),long=z.string().max(3000),id=z.string().max(100);
export const designSchema=z.object({background:short,primary:short,font:z.enum(['Georgia','Arial','Verdana']),radius:z.number().min(0).max(40),columns:z.number().int().min(1).max(3),fontSize:z.number().min(12).max(24),spacing:z.number().min(0).max(40),banner:short,header:z.enum(['center','left']),card:z.enum(['card','list'])});
export const itemSchema=z.object({id,categoryId:id,name:short,ar:short,description:long,descriptionAr:long,price:z.number().min(0).max(100000),discount:z.number().min(0).max(100000),image:long,available:z.boolean(),featured:z.boolean(),ingredients:long,allergens:short,calories:z.number().min(0).max(10000),spicy:z.number().min(0).max(3),dietary:short,hidden:z.boolean()});
export const menuSchema=z.object({id,name:short,slug:z.string().regex(/^[a-z0-9-]+$/).max(100),design:designSchema,categories:z.array(z.object({id,name:short,ar:short})).max(100),items:z.array(itemSchema).max(1000)});
export const stateSchema=z.object({revision:z.number().int(),profile:z.object({name:short,ar:short,description:long,descriptionAr:long,phone:short,address:long,hours:long,social:long,logo:long,branches:z.array(short).max(30)}),menus:z.array(menuSchema).min(1).max(30),themes:z.array(z.object({id,name:short,design:designSchema})).max(50)});
export type Menu=z.infer<typeof menuSchema>;export type Item=z.infer<typeof itemSchema>;export type State=z.infer<typeof stateSchema>;
export const baseDesign={background:'#faf7ee',primary:'#3e6347',font:'Georgia' as const,radius:12,columns:1,fontSize:16,spacing:16,banner:'Seasonal ingredients. Thoughtfully made.',header:'center' as const,card:'card' as const};
export function seed():State{const categoryId=crypto.randomUUID();return {revision:0,profile:{name:'Olive & Ember',ar:'زيتون وجمر',description:'Seasonal Mediterranean cooking, made with care.',descriptionAr:'مأكولات متوسطية موسمية، محضرة بعناية.',phone:'+962 6 555 0100',address:'Downtown, Amman',hours:'Daily · 9:00 AM – 11:00 PM',social:'',logo:'',branches:['Downtown']},themes:[],menus:[{id:crypto.randomUUID(),name:'Main Menu',slug:'main-menu',design:baseDesign,categories:[{id:categoryId,name:'From the kitchen',ar:'من المطبخ'}],items:[['Burrata & heirloom tomato','بوراتا وطماطم',14,'Creamy burrata, ripe tomatoes, basil and olive oil.'],['Wild mushroom risotto','ريزوتو الفطر',24,'Arborio rice, woodland mushrooms and aged parmesan.'],['Wood-fired sea bass','سمك قاروص مشوي',32,'Fresh sea bass, lemon, herbs and seasonal vegetables.']].map(([name,ar,price,description])=>({id:crypto.randomUUID(),categoryId,name:String(name),ar:String(ar),price:Number(price),description:String(description),descriptionAr:'',discount:0,image:String(name).startsWith('Burrata')?'https://images.unsplash.com/photo-1760023570385-ee484f7076b3?auto=format&fit=crop&w=800&q=80':String(name).startsWith('Wild')?'https://images.pexels.com/photos/5638527/pexels-photo-5638527.jpeg?auto=compress&w=800':'',available:true,featured:false,ingredients:'',allergens:'',calories:0,spicy:0,dietary:'',hidden:false}))}]}}

